version: "3.8"

services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "bash", "-c", "nc -z localhost 6379 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  localstack:
    image: localstack/localstack:1.4
    container_name: localstack
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    healthcheck:
      test: ["CMD", "bash", "-c", "curl -fsS http://localhost:4566/health || curl -fsS http://localhost:4566/_localstack/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 10s

  login-service:
    build:
      context: ./LoginService
      dockerfile: Dockerfile
    container_name: login-service
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - localstack
    environment:
      SPRING_DATA_REDIS_HOST: redis
      WAIT_HOSTS: redis:6379
      JAVA_TOOL_OPTIONS: "-Dspring.data.redis.host=redis -Dnetty.resolver.dns.useJdkResolver=true -Djava.net.preferIPv4Stack=true"
    restart: unless-stopped

  transaction-service:
    build:
      context: ./TransactionService
      dockerfile: Dockerfile
    container_name: transaction-service
    ports:
      - "8080:8080"
    depends_on:
      - login-service
      - localstack
      - mongo
    environment:
      - WAIT_HOSTS=localstack:4566,mongo:27017
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017
      - LOGIN_SERVICE_URL=http://login-service:8081/api/v1/auth
      - AWS_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - SQS_QUEUE_URL=http://localstack:4566/000000000000/transactions
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

    restart: unless-stopped

  game-service:
    build:
      context: ./GameService
      dockerfile: Dockerfile
    container_name: game-service
    ports:
      - "8082:8082"
    depends_on:
      mongo:
        condition: service_healthy
      localstack:
        condition: service_healthy
    environment:
      - AWS_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - SQS_QUEUE_URL=http://localstack:4566/000000000000/transactions
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/game_db
      - JAVA_TOOL_OPTIONS=-Dspring.data.mongodb.uri=mongodb://mongo:27017/game_db -Daws.sqs.endpoint=http://localstack:4566 -Daws.sqs.queue-url=http://localstack:4566/000000000000/transactions
      - WAIT_HOSTS=localstack:4566,mongo:27017
    restart: unless-stopped

volumes:
  mongo-data:
    driver: local